### ISSUE TITLE
segment_segment_intersect problem

### ISSUE THREAD

**Issue by avaxman** [libigl/libigl#1256] opened 2019-07-15 19:33 UTC
#### Describe your issue

Link to issue raised in Directional but pertaining to libigl. TL;DR: igl:segment_intersect is apparently deprecated, and the replacement function segment_segment_intersect doesn't work like the original (it gets stuck tracing; see screenshot attached).

https://github.com/avaxman/Directional/issues/19#issue-464778006

#### Check all that apply (change to `[x]`)
- [ ] Windows
- [X] Mac OS X
- [ ] Linux
- [ ] I have tried the `dev` branch and the problem persists

See https://libigl.github.io/CONTRIBUTING/#bugreport for more tips.

**Comment by avaxman** [comment] 2019-07-15 19:34
![image](https://user-images.githubusercontent.com/8985720/61243434-3d556000-a748-11e9-8275-c0c0cc2186fb.png)

**Comment by jdumas** [comment] 2019-07-15 20:36
This looks like a duplicate of #1042. The function `segment_intersect` has been renamed `segment_segment_intersect` in #1131.

**Closed** 2019-07-15 20:37 UTC
Labels: duplicate

**Comment by jdumas** [comment] 2019-07-15 20:51
Note that we could modify `segment_segment_intersect` to accept two different epsilon arguments, the first one used to check for parallel lines, the second used for the tolerance on the `t` and `u` parameters. In practice it seems for now that adding an epsilon of `-1e-6` in `directional::streamlines_next()` fixes the problem somehow?

**Comment by avaxman** [comment] 2019-07-15 20:58
Yes this seemed to do the trick. I will have to look a bit more under the hood later. Thanks.

**Comment by avaxman** [comment] 2022-09-26 22:51
There is a different problem pertaining to this function: it only considers "single point" as having intersected. When segments overlap, partially or fully, is returns false which might give the wrong result in context.
