### ISSUE TITLE
VS 2015 error C2131: expression did not evaluate to a constant

### ISSUE THREAD

**Issue by dpshamonin** [libigl/libigl#1226] opened 2019-06-13 13:02 UTC
#### Describe your issue
Dear Devs,
There is a compilation error in 
libigl\src\include\igl\opengl\glfw\imgui\ImGuiTraits.h
for Visual Studio 2015 update 3, see below:

>libigl\src\include\igl\opengl\glfw\imgui\ImGuiTraits.h(29): error C2131: expression did not evaluate to a constant
libigl\src\include\igl\opengl\glfw\imgui\ImGuiTraits.h(29): note: failure was caused by unevaluable pointer value
...
libigl\src\include\igl\opengl\glfw\imgui\ImGuiTraits.h(64): error C2131: expression did not evaluate to a constant
libigl\src\include\igl\opengl\glfw\imgui\ImGuiTraits.h(64): note: failure was caused by unevaluable pointer value

It appears can be fixed by declaring format as a pointer instead of array:

    static constexpr char *format = "%d";

at the following line:

  https://github.com/libigl/libigl/blob/master/include/igl/opengl/glfw/imgui/ImGuiTraits.h#L29

And five other places in this file. It looks like a Visual Studio 2015 compiler bug,

Regards,
Denis
...

#### Check all that apply (change to `[x]`)
- [x ] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] I have tried the `dev` branch and the problem persists

See https://libigl.github.io/CONTRIBUTING/#bugreport for more tips.

**Comment by jdumas** [comment] 2019-06-13 13:05
This has already been discussed in #964. If you can find a way that compiles with both VS2015 and VS2017 (and also VS2019), we'd be happy to merge a PR. In the meantime, I prefer to keep the solution that works with more recent versions of MSVC.

**Comment by dpshamonin** [comment] 2019-06-13 13:16
Thanks for reply Jérémie. 
The correct way of fixing it for both compilers VS 2015, 2017 ... is this:

    static constexpr const char *format = "%d";

The pointer is `constexpr `and it points to `const char`.

**Comment by jdumas** [comment] 2019-06-13 13:19
This is what we had before (see thread in #964), and apparently it was causing issues. I'll have to try it again to confirm.

**Comment by dpshamonin** [comment] 2019-06-14 09:44
Did you already try the combination of _both_ `constexpr` + `const `
should be: 

    static constexpr const char *format = "%d";

not 

    static constexpr char *format = "%d";

I don't have any issues with this minimum example on any compiler.
https://godbolt.org/z/WvOsma

Anyway, how are you planning to access `private ` member `format` from the `class`?
https://godbolt.org/z/Xkn-Iu

**Comment by jdumas** [comment] 2019-06-14 12:20
I didn't know you could combine both `constexpr` and `const`. That's kind of silly as one would imply the other. You're right about the private part though, those `class` should probably be `struct` instead.

**Comment by dpshamonin** [comment] 2019-06-14 13:28
The pointer is `const `at compile time with `constexpr `, but what it points to, still could be modified. So you make it `const`.

**Comment by jdumas** [comment] 2019-06-14 14:03
Oh, right. Good remark! If you want to open a PR for that I can merge it.

**Comment by dpshamonin** [comment] 2019-06-14 14:16
Ok, I will try next week, have a nice weekend.

**Comment by zhfsu** [comment] 2019-07-13 22:57
Just to confirm, is the fix an array version like `static constexpr const char format [] = "%.6f";` but not the pointer version as suggested by dpshamonin? I personally prefer the former. PS: when will the fix be merged into the master branch? I checked yesterday and the issue still persists. Thanks.

**Comment by jdumas** [comment] 2019-07-14 05:08
The master branch is updated every 6 months or so when we label a new stable version. Until then you can use the `dev` branch, which receives regular updates.

**Comment by N-Dekker** [comment] 2019-07-14 09:51
@zhfsu Regarding your first question: This issue is actually fixed by "the pointer version as suggested by @dpshamonin: 4228447e3cbdf74750558eb135777cd055a78744

I just tried your "array version" as well:

    struct Trait
    {
      // static constexpr char format_original[] = "%d"; // <== MSVC2015 error C2131
    
      static constexpr const char* format_dpshamonin = "%d";
      static constexpr const char format_zhfsu[] = "%d";
    };

    int main()
    {
      printf(Trait::format_dpshamonin, 42);
      printf(Trait::format_zhfsu, 42);
    }

Unfortunately clang 3.8 gave an error on your array version, at https://rextester.com/FJAAC72954 : 

> undefined reference to `Trait::format_zhfsu'

The pointer version still appears to compile well. So I would rather stick with the pointer version as suggested by @dpshamonin at the dev branch (4228447e3cbdf74750558eb135777cd055a78744)

**Comment by phamminhkhac** [comment] 2021-07-16 02:41
same error at latest version:

C:\Users\Anynomous\.vscode\extensions\liximomo.sftp-1.12.9\node_modules\ssh2>node install.js
gyp info it worked if it ends with ok
gyp info using node-gyp@8.1.0
gyp info using node@12.18.2 | win32 | x64
gyp info find Python using Python version 3.9.5 found at "C:\Program Files\Python39\python.exe"
gyp info find VS using VS2019 (16.8.30717.126) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\Program Files\Python39\python.exe
gyp info spawn args [
gyp info spawn args   'C:\\Users\\Anynomous\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Anynomous\\.vscode\\extensions\\liximomo.sftp-1.12.9\\node_modules\\ssh2\\lib\\protocol\\crypto\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Anynomous\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Anynomous\\AppData\\Local\\node-gyp\\Cache\\12.18.2\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Anynomous\\AppData\\Local\\node-gyp\\Cache\\12.18.2',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\Anynomous\\AppData\\Roaming\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\Anynomous\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\12.18.2\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\Anynomous\\.vscode\\extensions\\liximomo.sftp-1.12.9\\node_modules\\ssh2\\lib\\protocol\\crypto',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\Anynomous\\.vscode\\extensions\\liximomo.sftp-1.12.9\\node_modules\\ssh2\\lib\\protocol\\crypto\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\MSBuild.exe
gyp info spawn args [
gyp info spawn args   'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64'
gyp info spawn args ]
Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
  binding.cc
C:\Users\Anynomous\.vscode\extensions\liximomo.sftp-1.12.9\node_modules\ssh2\lib\protocol\crypto\src\binding.cc(1718,28
): error C2131: `expression did not evaluate to a constant` [C:\Users\Anynomous\.vscode\extensions\liximomo.sftp-1.12.9\n
ode_modules\ssh2\lib\protocol\crypto\build\sshcrypto.vcxproj]
C:\Users\Anynomous\.vscode\extensions\liximomo.sftp-1.12.9\node_modules\ssh2\lib\protocol\crypto\src\binding.cc(1718,28
): message : failure was caused by a read of a variable outside its lifetime [C:\Users\Anynomous\.vscode\extensions\lix
imomo.sftp-1.12.9\node_modules\ssh2\lib\protocol\crypto\build\sshcrypto.vcxproj]
C:\Users\Anynomous\.vscode\extensions\liximomo.sftp-1.12.9\node_modules\ssh2\lib\protocol\crypto\src\binding.cc(1718,28
): message : see usage of 'this' [C:\Users\Anynomous\.vscode\extensions\liximomo.sftp-1.12.9\node_modules\ssh2\lib\prot
ocol\crypto\build\sshcrypto.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\MSBuild.exe" failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Anynomous\AppData\Roaming\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Windows_NT 10.0.19043
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Anynomous\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "--target=v12.18.2" "rebuild"
gyp ERR! cwd C:\Users\Anynomous\.vscode\extensions\liximomo.sftp-1.12.9\node_modules\ssh2\lib\protocol\crypto
gyp ERR! node -v v12.18.2
gyp ERR! node-gyp -v v8.1.0
gyp ERR! not ok
Failed to build optional crypto binding

**Comment by alecjacobson** [comment] 2023-08-28 22:23
Closing due to inactivity if this is still in progress feel free to reopen.

**Closed by alecjacobson** 2023-08-28 22:23 UTC
Labels: compilation, windows
