### ISSUE TITLE
Tutorial Example 504_NRosyField problem

### ISSUE THREAD

**Issue by csv610** [libigl/libigl#446] opened 2017-01-16 20:36 UTC
Hello 

It seems that the tutorial example 504_NRosyField produces segmentation fault:
igl::viewer::Viewer usage:
  [drag]  Rotate scene
  A,a     Toggle animation (tight draw loop)
  F,f     Toggle face based
  I,i     Toggle invert normals
  L,l     Toggle wireframe
  O,o     Toggle orthographic/perspective projection
  T,t     Toggle filled faces
  Z       Snap to canonical view
  [,]     Toggle between rotation control types (e.g. trackball, two-axis
          valuator with fixed up)
  ;       Toggle vertex labels
  :       Toggle face labels
solve
 Initital dimension: 3744 x 3744, number of constraints: 0 use reordering: 1
Eliminated dimension: 3744 x 3744
#nonzeros: 16222
# integer    variables: 1249
# continuous variables: 2495
Segmentation fault

**Comment by alecjacobson** [comment] 2017-01-26 13:42
This seems to be a duplicate of https://github.com/libigl/libigl/issues/447

**Closed by alecjacobson** 2017-01-26 13:42 UTC
