### ISSUE TITLE
Eigen/Dense not found when compiling Python bindings

### ISSUE THREAD

**Issue by mibieri** [libigl/libigl#622] opened 2017-10-21 10:11 UTC
I'm currently trying to (re-)build the Python bindings. I get an error because it can not find `Eigen/Dense`. I might be wrong, but I don't remember that I ever had to configure anything about Eigen when I compiled libigl Python bindings earlier this year. Wasn't it just included in libigl? Or what do I need to configure in order to find Eigen? I can't find a variable related to Eigen includes when using ccmake in libigl/python/build.

`[  0%] Building CXX object CMakeFiles/pyigl.dir/python_shared.cpp.o
In file included from /users/me/libs/libigl/libigl/python/python_shared.cpp:8:0:
/users/me/libs/libigl/libigl/python/python_shared.h:19:23: fatal error: Eigen/Dense: No such file or directory`

**Comment by danielepanozzo** [comment] 2017-10-25 01:11
This is very strange. I cannot reproduce it and the autobuilds are working with the current version. Which operating system are you using? Can you try to clone fresh and rerun cmake?

**Comment by collord** [comment] 2017-10-29 03:07
I'm having similar trouble trying to do a fresh clone and compile on Win8/VS2017/MSBuild 15. (I'm just trying to get the python module up on my windows machine--I had success some months ago on my mac.) I was expecting to see an eigen repository directly in external or in includes, or somewhere, but the only place I find eigen source/headers after git clone --recursive is within external/nanogui/modules/ext. 

BUT I only see the above error if I pare down the options in CMakeLists.txt i.e. to only have ON the LIBIGL_WITH_PYTHON option. If I run cmake with the default CMakeLists.txt I am treated to this:

"c:\blah\libigl\libigl\python\build\ALL_BUILD.vcxproj" (default target) (1) ->
"c:\blah\libigl\libigl\python\build\pyigl.vcxproj" (default target) (17) ->
(ClCompile target) ->
  c:\blah\libigl\libigl\python\modules/py_typedefs.cpp(8): error C2440: 'type cast': cannot convert from 'overloaded-function' to 'Eigen::Quaterniond &(__thiscall std::vector<Eigen::Quaterniond,Eigen::aligned_allocator<Eigen::Quaterniond>>::* )(void)' (compiling source file c:\blah\libigl\libigl\python\py_igl.cpp) [c:\blah\libigl\libigl\python\build\pyigl.vcxproj]
  c:\blah\libigl\libigl\python\modules/py_typedefs.cpp(8): error C2672: 'pybind11::class_<RotationList>::def': no matching overloaded function found (compiling source file c:\blah\libigl\libigl\python\py_igl.cpp) [c:\blah\libigl\libigl\python\build\pyigl.vcxproj]
  c:\blah\libigl\libigl\python\modules/py_typedefs.cpp(8): error C2784: 'pybind11::class_<RotationList> &pybind11::class_<RotationList>::def(const pybind11::detail::init_alias<Args...> &,const Extra &...)': could not deduce template argument for 'const pybind11::detail::init_alias<Args...> &' from 'const char [5]' (compiling source file c:\blah\libigl\libigl\python\py_igl.cpp) [c:\blah\libigl\libigl\python\build\pyigl.vcxproj]
  c:\blah\libigl\libigl\python\modules/py_typedefs.cpp(8): error C2784: 'pybind11::class_<RotationList> &pybind11::class_<RotationList>::def(const pybind11::detail::init<Args...> &,const Extra &...)': could not deduce template argument for 'const pybind11::detail::init<Args...> &' from 'const char [5]' (compiling source file c:\blah\libigl\libigl\python\py_igl.cpp) [c:\blah\libigl\libigl\python\build\pyigl.vcxproj]
  c:\blah\libigl\libigl\python\modules/py_typedefs.cpp(8): error C2784: 'pybind11::class_<RotationList> &pybind11::class_<RotationList>::def(const pybind11::detail::op_<id,ot,L,R> &,const Extra &...)': could not deduce template argument for 'const pybind11::detail::op_<id,ot,L,R> &' from 'const char [5]' (compiling source file c:\blah\libigl\libigl\python\py_igl.cpp) [c:\blah\libigl\libigl\python\build\pyigl.vcxproj]
  c:\blah\libigl\libigl\python\modules/py_typedefs.cpp(8): error C2780: 'pybind11::class_<RotationList> &pybind11::class_<RotationList>::def(const char *,Func &&,const Extra &...)': expects 3 arguments - 1 provided (compiling source file c:\blah\libigl\libigl\python\py_igl.cpp) [c:\blah\libigl\libigl\python\build\pyigl.vcxproj]
  c:\blah\libigl\libigl\python\modules/py_typedefs.cpp(8): error C2228: left of '.def' must have class/struct/union (compiling source file c:\blah\libigl\libigl\python\py_igl.cpp) [c:\blah\libigl\libigl\python\build\pyigl.vcxproj]
  c:\blah\libigl\libigl\python\modules/py_typedefs.cpp(16): error C2228: left of '.def' must have class/struct/union (compiling source file c:\blah\libigl\libigl\python\py_igl.cpp) [c:\blah\libigl\libigl\python\build\pyigl.vcxproj]
  c:\blah\libigl\libigl\python\modules/py_typedefs.cpp(17): error C2228: left of '.def' must have class/struct/union (compiling source file c:\blah\libigl\libigl\python\py_igl.cpp) [c:\blah\libigl\libigl\python\build\pyigl.vcxproj]
  c:\blah\libigl\libigl\python\modules/py_typedefs.cpp(18): error C2228: left of '.def' must have class/struct/union (compiling source file c:\blah\libigl\libigl\python\py_igl.cpp) [c:\blah\libigl\libigl\python\build\pyigl.vcxproj]

**Comment by universewill** [comment] 2018-10-29 07:36
I encountered same problem on my MacBook. I changed the cmakelist.txt in python folder to install LIBIGL_WITH_TRIANGLE, however , the error still exists.
How to solve this? 

@patrikhuber

**Comment by patrikhuber** [comment] 2018-10-29 10:18
@universewill I wasn't able to resolve this. What I did was expose the libigl functions that I needed by myself in my own Python module, with pybind11 and its Eigen bindings.

libigl have recently pushed a lighter version of the repository, and I think some CMake-stuff was improved/rewritten too, so maybe you got better luck with the latest master branch now? They also have a rewrite of their Python bindings on their agenda but I don't know if these landed in master yet.

**Comment by jdumas** [comment] 2018-10-29 12:22
The new python bindings are currently WIP in the `dev-python` branch. We don't have any ETA for when they can be merged into the main `dev` branch yet. Unfortunately, this means we don't have much incentive to fix the existing bindings given that new ones are in the work, but I understand this may be frustrating. You can either check out an earlier version (v1.3.1) to see if the problem was recently introduced, or be more adventurous and try the new `dev-python` branch.

**Comment by gsssrao** [comment] 2019-03-29 01:55
@jdumas yes, the current `dev-python` branch has a missing declaration.

Adding the following declaration to the `include/igl/principal_curvature.h` makes it compile:
```
template <
  typename DerivedV,
  typename DerivedF,
  typename DerivedPD1,
  typename DerivedPD2,
  typename DerivedPV1,
  typename DerivedPV2,
  typename Index>
IGL_INLINE void principal_curvature(
  const Eigen::MatrixBase<DerivedV>& V,
  const Eigen::MatrixBase<DerivedF>& F,
  Eigen::PlainObjectBase<DerivedPD1>& PD1,
  Eigen::PlainObjectBase<DerivedPD2>& PD2,
  Eigen::PlainObjectBase<DerivedPV1>& PV1,
  Eigen::PlainObjectBase<DerivedPV2>& PV2,
  std::vector<Index>& bad_vertices,
  unsigned radius = 5,
  bool useKring = true);
```

But the bindings don't seem to work. I am building directly from the root dir using `LIBIGL_USE_STATIC_LIBRARY=ON`. Are there any new instructions on building the Python bindings say from the `dev` branch?

**Comment by jdumas** [comment] 2019-03-29 23:04
The current python bindings in `dev` branch should compile fine by now. Development on the "new" bindings were stalled for a while but I believe @fwilliams has some incentive to ship them by Siggraph this summer.

**Comment by teseoch** [comment] 2020-02-20 15:45
this issue involves the old bindings which have been discontinued, plz refer to https://libigl.github.io/libigl-python-bindings/ for the new version.

**Closed by teseoch** 2020-02-20 15:45 UTC
Labels: compilation, python
