### ISSUE TITLE
Exception thrown in 505MIQ

### ISSUE THREAD

**Issue by ada-hs** [libigl/libigl#440] opened 2017-01-06 07:09 UTC
hi!,
when I compile the example 505, exception thrown...and the console output looks like this:
![image](https://cloud.githubusercontent.com/assets/11327318/21710175/fe67837e-d421-11e6-91e1-1bb0e1f87738.png)

Exception thrown at 0x000000006DA9D847 (libopenblas.dll) in 505_MIQ_bin.exe: 0xC0000005: Access violation reading location 0xFFFFFFFFFFFFFFFF.

The other examples are good except this, any help?

**Comment by copyme** [comment] 2018-10-23 11:46
It works well here. The issue is old and I suggest to close it. Most likely the issue is not relevant anymore.

**Comment by jdumas** [comment] 2018-10-23 12:31
@copyme are you also on Windows?

**Comment by copyme** [comment] 2018-10-23 12:41
@jdumas for now nope. But if @ada-hs could provide more information about used compiler and version of Windows (it looks like win7 SP1, right?). I could test it here. For now I do not think so we can reproduce this issue. Too few information.

**Comment by jdumas** [comment] 2018-10-23 12:54
Sure. If @ada-hs doesn't update us on this in a week or so, I can tag is as "cannot-reproduce" and close it.

**Comment by ada-hs** [comment] 2018-10-29 07:48
Thanks for your reply. just close this old issue.

**Closed** 2018-10-29 12:22 UTC
