### ISSUE TITLE
segfaults in CoMISo on Windows MSVC 2017 x64 due to inclusion of binary-incompatible pre-built BLAS libraries

### ISSUE THREAD

**Issue by evouga** [libigl/libigl#1050] opened 2018-12-21 05:46 UTC
CoMISo requires the GMM++ library, which in turn requires BLAS. Currently libigl is configured on Windows to make use of precompiled BLAS dynamic libraries bundled in `libigl/external/CoMISo/ext`.

This is a dubious setup because the precompiled libraries are configured to work with the MinGW toolchain and do not work (segfault) when called from libigl code compiled using the native Microsoft compilers.

Deleting the BLAS libraries from CoMISo and linking instead to OpenBLAS compiled from source fixes the issue.

#### Check all that apply (change to `[x]`)
- [X] Windows
- [ ] Mac OS X
- [ ] Linux

See <https://libigl.github.io/CONTRIBUTING/#bugreport> for more tips.

**Comment by jdumas** [comment] 2018-12-21 07:59
Wait but we _do_ have unit tests that are compiling and running fine on AppVeyor with the MSVC toolchain. Do you have a more precise use-case in mind, or a unit test that would crash under the current setup? If so, we could certainly accept PRs improving this, but I don't think the libigl fork of CoMISo is very well maintained either.

**Comment by evouga** [comment] 2018-12-21 08:44
I don't understand what kind of "unit test" you want me to submit. Some kind of Docker image with Windows and the entire development tool suite?

I am using Windows 10 64-bit, MSVC 2017 x64 compiled in Release mode. Just try any of the examples that use CoMISo.

In any case, it is a fundamentally bad idea to try to link together object code compiled using different vendors with different versions of libc, even if it happens to work for some specific compiler versions/architectures/flags. Several reasons are listed here: http://www.mingw.org/wiki/Interoperability_of_Libraries_Created_by_Different_Compiler_Brands

Probably the least-effort fix is to do the same thing for Windows as you do for other operating systems in the CoMISo cmakelists: ask cmake to find_package(BLAS) and leave it to the user to properly install and configure a BLAS implementation. Of course it is more user-friendly if libigl builds BLAS from source.

**Comment by evouga** [comment] 2018-12-21 08:48
This one for example: https://github.com/libigl/libigl/tree/master/tutorial/505_MIQ

**Comment by jdumas** [comment] 2018-12-21 15:47
Well, we have unit tests that use CoMISo, which compile and run on Windows on AppVeyor. I don't see why a docker image would be any different. If you're experiencing a crash on your Windows machine, you should be able to add a unit test on AppVeyor that reproduces the crash. This would also ensure that we don't break it again by chance in the future if we make any modification to this part of the code.

Afaik DLLs on Windows were pretty flexibles in terms of being able to run with different versions of libc or libstd, but maybe it's an incorrect assumption. At the very least, the reason why there is no `find_package(BLAS)` on the Windows build is that Windows user in general don't know how to install a package (for the simple reason that there is no proper package manager on Windows). So we'd like to provide hassle-free experience on that front as much as possible. But feel free to suggest any change to the compilation process that doesn't break this hassle-free prerequisite, and we'd be happy to take a look.

**Comment by evouga** [comment] 2018-12-21 18:36
I don't know how to "add a unit test on AppVeyor" and unfortunately do not have the time to figure it out. I've described my system configuration, explained why the current handling of BLAS in libigl is unsound both in theory and practice, and suggested several ways to fix. In particular, one principled solution that remains hassle-free for the user is for libigl to fetch and compile OpenBLAS from source. Maybe rewriting CoMISo to use Eigen instead of GMM is even better,  but may entail a lot of effort.

If this is being classified as `wontfix`, I've edited the title to at least make it easier for other Windows getting mysterious segfaults to locate the description of the problem and solution.

**Comment by fwilliams** [comment] 2018-12-21 22:04
@jdumas, AppVeyor tests one particular configuration on Windows. Just because it works there, doesn't mean it works everywhere. I had a colleague on Windows who hit this same problem IIRC. @evouga is right and shipping a binary is a poor solution to the problem and we should keep this issue open. 

@evouga if you want to take a swing at implementing a source build of OpenBLAS here are some pointers. It would definitely be a much appreciated PR if you do it!

1. Clone the `dev` branch of libigl
2. Add a function in [/cmake/LibiglDownloadExternal.cmake](https://github.com/libigl/libigl/blob/master/cmake/LibiglDownloadExternal.cmake) which downloads OpenBLAS
3. The CoMISo build code can be found [here](https://github.com/libigl/libigl/blob/master/cmake/libigl.cmake#L237). Add a hook that downloads (using the function you added in step 1.) and compiles OpenBLAS here if you're on Windows.
4. Send a PR and make sure the continuous integration passes (builds are triggered automatically when you send your PR).

Also, if ever you need to change how AppVeyor builds, you can do so by editing .appveyor.yaml [here](https://github.com/libigl/libigl/blob/master/.appveyor.yml). The docs for editing that file are [here](https://www.appveyor.com/docs/appveyor-yml/), though you should not need to do so to implement a source build of OpenBLAS.

**Comment by jdumas** [comment] 2018-12-21 23:36
@evouga, well I don't have time to "deal with this" either. Not being a Windows user myself, I have to boot on a separate partition to check things up everytime someone is unhappy about the current situation on Windows. I have zero incentive to fix the Windows build myself, so unless someone else (you?) whips up a PR to address the issue, I wouldn't expect a fix anytime soon.

Even if the current build is imperfect, the fact that is works on AppVeyor is the only objective gauge we have to make sure "stuff works" on Windows (it's not perfect, but it's an indication). For example, the AppVeyor image builds in x64 using MSVC 2017, so I don't see why it would magically behave different on any other Windows machine. Explain what's different between the configurations, and maybe we can add another supported configuration in AppVeyor.

As for rewriting CoMISo to use Eigen, well you can certainly try to bring it up to the original authors of the CoMISo library :D

**Comment by jdumas** [comment] 2018-12-22 11:03
Please note that unit tests may not enabled in the current `dev` branch, but I have an active PRs #996 that enables them (mostly focused on the CGAL build). The PR is not merged because there are some erratic failures cases (not Windows nor CoMISo related though). But the tests for Windows are built in Debug mode on this PR. It's easy to add a build in Release + Debug to see whether it segfaults in Release on AppVeyor (it should, if you're experiencing the issue).

**Comment by huxingyi** [comment] 2020-06-15 09:21
I can confirm, on Windows 10/Visual Studio 2017 64bit, Intel i7-9750H, the `comiso::miq` will crash if link to `CoMISo\ext\OpenBLAS-v0.2.14-Win64-int64\lib\libopenblas.dll.a.lib`.
There is a workaround to bypass the `openblas` for 505_MIQ, use `daxpy_`, `dnrm2_`, `ddot_`  from clapack without link to `openblas`, the performance is even slightly better.
```
extern "C" {
    // http://www.netlib.org/clapack/
    
    typedef long int integer;
    typedef unsigned long int uinteger;
    typedef char* address;
    typedef short int shortint;
    typedef float real;
    typedef double doublereal;

    int daxpy_(integer* n,
               doublereal* da,
               doublereal* dx,
               integer* incx,
               doublereal* dy,
               integer* incy) {
      /* System generated locals */
      integer i__1;

      /* Local variables */
      static thread_local integer i, m, ix, iy, mp1;

    /*     constant times a vector plus a vector.
           uses unrolled loops for increments equal to one.
           jack dongarra, linpack, 3/11/78.
           modified 12/3/93, array(1) declarations changed to array(*)



       Parameter adjustments
           Function Body */
    #define DY(I) dy[(I)-1]
    #define DX(I) dx[(I)-1]

      if (*n <= 0) {
        return 0;
      }
      if (*da == 0.) {
        return 0;
      }
      if (*incx == 1 && *incy == 1) {
        goto L20;
      }

      /*        code for unequal increments or equal increments
                  not equal to 1 */

      ix = 1;
      iy = 1;
      if (*incx < 0) {
        ix = (-(*n) + 1) * *incx + 1;
      }
      if (*incy < 0) {
        iy = (-(*n) + 1) * *incy + 1;
      }
      i__1 = *n;
      for (i = 1; i <= *n; ++i) {
        DY(iy) += *da * DX(ix);
        ix += *incx;
        iy += *incy;
        /* L10: */
      }
      return 0;

    /*        code for both increments equal to 1


              clean-up loop */

    L20:
      m = *n % 4;
      if (m == 0) {
        goto L40;
      }
      i__1 = m;
      for (i = 1; i <= m; ++i) {
        DY(i) += *da * DX(i);
        /* L30: */
      }
      if (*n < 4) {
        return 0;
      }
    L40:
      mp1 = m + 1;
      i__1 = *n;
      for (i = mp1; i <= *n; i += 4) {
        DY(i) += *da * DX(i);
        DY(i + 1) += *da * DX(i + 1);
        DY(i + 2) += *da * DX(i + 2);
        DY(i + 3) += *da * DX(i + 3);
        /* L50: */
      }
      return 0;
    } /* daxpy_ */

    doublereal ddot_(integer* n,
                     doublereal* dx,
                     integer* incx,
                     doublereal* dy,
                     integer* incy) {
      /* System generated locals */
      integer i__1;
      doublereal ret_val;

      /* Local variables */
      static thread_local integer i, m;
      static thread_local doublereal dtemp;
      static thread_local integer ix, iy, mp1;

    /*     forms the dot product of two vectors.
           uses unrolled loops for increments equal to one.
           jack dongarra, linpack, 3/11/78.
           modified 12/3/93, array(1) declarations changed to array(*)



       Parameter adjustments
           Function Body */
    #define DY(I) dy[(I)-1]
    #define DX(I) dx[(I)-1]

      ret_val = 0.;
      dtemp = 0.;
      if (*n <= 0) {
        return ret_val;
      }
      if (*incx == 1 && *incy == 1) {
        goto L20;
      }

      /*        code for unequal increments or equal increments
                  not equal to 1 */

      ix = 1;
      iy = 1;
      if (*incx < 0) {
        ix = (-(*n) + 1) * *incx + 1;
      }
      if (*incy < 0) {
        iy = (-(*n) + 1) * *incy + 1;
      }
      i__1 = *n;
      for (i = 1; i <= *n; ++i) {
        dtemp += DX(ix) * DY(iy);
        ix += *incx;
        iy += *incy;
        /* L10: */
      }
      ret_val = dtemp;
      return ret_val;

    /*        code for both increments equal to 1


              clean-up loop */

    L20:
      m = *n % 5;
      if (m == 0) {
        goto L40;
      }
      i__1 = m;
      for (i = 1; i <= m; ++i) {
        dtemp += DX(i) * DY(i);
        /* L30: */
      }
      if (*n < 5) {
        goto L60;
      }
    L40:
      mp1 = m + 1;
      i__1 = *n;
      for (i = mp1; i <= *n; i += 5) {
        dtemp = dtemp + DX(i) * DY(i) + DX(i + 1) * DY(i + 1) +
                DX(i + 2) * DY(i + 2) + DX(i + 3) * DY(i + 3) +
                DX(i + 4) * DY(i + 4);
        /* L50: */
      }
    L60:
      ret_val = dtemp;
      return ret_val;
    } /* ddot_ */

    doublereal dnrm2_(integer* n, doublereal* x, integer* incx) {
      /* System generated locals */
      integer i__1, i__2;
      doublereal ret_val, d__1;

      /* Builtin functions */
      double sqrt(doublereal);

      /* Local variables */
      static doublereal norm, scale, absxi;
      static integer ix;
      static doublereal ssq;

    /*  DNRM2 returns the euclidean norm of a vector via the function
        name, so that

           DNRM2 := sqrt( x'*x )



        -- This version written on 25-October-1982.
           Modified on 14-October-1993 to inline the call to DLASSQ.
           Sven Hammarling, Nag Ltd.



       Parameter adjustments
           Function Body */
    #define X(I) x[(I)-1]

      if (*n < 1 || *incx < 1) {
        norm = 0.;
      } else if (*n == 1) {
        norm = abs(X(1));
      } else {
        scale = 0.;
        ssq = 1.;
        /*        The following loop is equivalent to this call to the LAPACK

                  auxiliary routine:
                  CALL DLASSQ( N, X, INCX, SCALE, SSQ ) */

        i__1 = (*n - 1) * *incx + 1;
        i__2 = *incx;
        for (ix = 1;
             *incx < 0 ? ix >= (*n - 1) * *incx + 1 : ix <= (*n - 1) * *incx + 1;
             ix += *incx) {
          if (X(ix) != 0.) {
            absxi = (d__1 = X(ix), abs(d__1));
            if (scale < absxi) {
              /* Computing 2nd power */
              d__1 = scale / absxi;
              ssq = ssq * (d__1 * d__1) + 1.;
              scale = absxi;
            } else {
              /* Computing 2nd power */
              d__1 = absxi / scale;
              ssq += d__1 * d__1;
            }
          }
          /* L10: */
        }
        norm = scale * sqrt(ssq);
      }

      ret_val = norm;
      return ret_val;

      /*     End of DNRM2. */

    } /* dnrm2_ */
}
```

**Comment by zoharl3** [comment] 2020-07-15 18:27
@evouga is right. I have no idea what kind of tests you make, but on Windows it's a bad idea, and it's bound to crash. My quick solution:

I patched libigl\external\CoMISo\CMakeLists.txt to use mkl's blas:
  target_link_directories(CoMISo PUBLIC "c:/prj-external-libs/mkl2019/")
  target_link_libraries(CoMISo PUBLIC mkl_intel_thread_dll.lib mkl_core_dll.lib mkl_intel_lp64_dll.lib)

where intel mkl lib should be free.

**Comment by evouga** [comment] 2022-01-23 08:07
I'm still having this issue. Here is my current workaround process, in case it helps others:

1. Download and install Intel OneAPI
2. Compile your code and let CMake download the standard libigl library
3. Go and fix CoMISo's config scripts. In particular, in `build/_deps/libigl-src/external/CoMISo/CMakeLists.txt`, change the WIN32 section to be

```
if(WIN32)
  target_compile_definitions(CoMISo PRIVATE -D_USE_MATH_DEFINES -DNOMINMAX)
  target_compile_options(CoMISo PUBLIC /D_SCL_SECURE_NO_DEPRECATE)
  find_package(BLAS REQUIRED)
  target_link_libraries(CoMISo PUBLIC ${BLAS_LIBRARIES})
endif()
```

4. Go to the OneAPI command prompt (from the start menu), navigate to your build folder, and run cmake. You must use the OneAPI command prompt---the CMake GUI does not have the correct system paths configured to find MKL BLAS.

5. You can now go back to the CMake GUI and reload the cache (which will contain the correct MKL paths), or go compile your code, etc.

**Comment by jdumas** [comment] 2022-01-23 08:41
If you want a simpler way to setup MKL in a CMake project, you can use the following [mkl.cmake](https://github.com/adobe/lagrange/blob/aeebd56eaaf9d3ca448174501781c8bedaa05b63/cmake/recipes/external/mkl.cmake#L12) file. To use it, simply put this `mkl.cmake` in a folder searched by `CMAKE_MODULE_PATH`, then write the following in your CMake project:
```cmake
include(mkl)
target_link_libraries(CoMISo PUBLIC mkl::mkl)
```

This will have CMake download the precompiled MKL libs automatically when configuring the project.

**Comment by alecjacobson** [comment] 2023-09-12 19:11
I think this has all improved with the new cmake.

**Closed by alecjacobson** 2023-09-12 19:11 UTC
Labels: unit-test-needed
