### ISSUE TITLE
glfw_objects missing when try to make projects with Xcode

### ISSUE THREAD

**Issue by ruoqingsun** [libigl/libigl#383] opened 2016-10-27 15:56 UTC
I am currently launching all the projects in Mac OS Sierra (version 10.12.1). Building with the "cmake, make" procedures works perfect. 

But when I tried "CMake -G Xcode ../" procedure to import everything into XCode project, it seems that in the building phase, no those C objects in glfw_objects or libglfw3.a is generated. 

![image](https://cloud.githubusercontent.com/assets/4344440/19774795/8d5eecfc-9c6e-11e6-8c4a-f999e00e7278.png)

And I get the following error after building failure in Xcode:
clang: error: no such file or directory: '/Users/ruoqing/Documents/GitHub/libigl/tutorial/build/libigl/glfw/src/Debug/libglfw3.a'

**Comment by alecjacobson** [comment] 2016-10-27 16:16
I'm not currently using Xcode and don't know how stable the cmake `-G
Xcode` is meant to be (though I thought it was stable). This is potentially
an issue with the way that the glfw cmake is set up. You might try first
seeing whether https://github.com/glfw/glfw compiles correctly using cmake
and Xcode this way.

**Comment by danielepanozzo** [comment] 2016-10-27 16:25
I can also reproduce this with the latest xcode and cmake. It is likely that they changed something in the new xcode build system and cmake has not been updated yet.

**Comment by ruoqingsun** [comment] 2016-10-28 10:34
I am currently using xcode 8 and cmake 3.7.0. The problem is I can successfully build the project, but when running the project, the project cannot check dependencies in the listed Makefiles to generate glfw objects. @danielepanozzo Which version of xcode and cmake are you applying in reproducing the project? How to let the xcode follow the dependencies listed in makefile?

**Comment by danielepanozzo** [comment] 2016-10-28 11:41
Sorry I was not clear. I meant that I can reproduce the *error*, I also cannot get it to follow the dependencies and I get the same problem with glfw that you have.

**Comment by metorm** [comment] 2017-12-28 11:24
I have posted a Temporary fix for this #673

**Comment by jdumas** [comment] 2018-01-06 04:30
Looks like this is an issue caused by CMake's *object* targets not playing well with the XCode generator. This is definitely a bug in CMake. In the meantime, @metorm could you try to replace (just to see if it compiles) the folder of glfw in the nanogui submodule by the latest [upstream version](https://github.com/glfw/glfw)?

**Comment by jdumas** [comment] 2018-03-11 01:12
This problem should be fixed in the latest version of libigl, as we now link against `glfw` from upstream, which is not defined as an `object` target in the CMake.

**Closed by jdumas** 2018-03-11 01:12 UTC
Labels: compilation, viewer
