### ISSUE TITLE
igl::copyleft::comiso::miq BadAllocation exception on Win10

### ISSUE THREAD

**Issue by LorenzG** [libigl/libigl#577] opened 2017-08-02 20:13 UTC
Hi guys,

I'm using LibIgl on three windows machines with the following configs:
- CGAL 4.9.1;
- eigen3 67e894c6cd8f
- boost 1.63

latest libigl and its dependencies from this github, in particular:
- COMISO
- gmm
- OpenBLAS

and the following libraries from mingw to make OpenBLAS work:

![image](https://user-images.githubusercontent.com/7131055/28888659-55acfe8a-77b9-11e7-963e-f3f1df647185.png)

I'm trying example 506_FrameField, it builds and run on my win7 machine, but on both of my win10 it throws a BadAllocation exception at:
**igl::copyleft::comiso::miq**

I've rebuilt COMISO, gmm and libigl targeting win 10.0.14393.0 and the issue stays.
This is kind of weird I guess, because the other calls to igl::copyleft::comiso::xxxx work such as
igl::copyleft::comiso::frame_field and igl::copyleft::comiso::nrosy

What am I missing?

If it's not something silly or a known issue I can try and do more checks.

Thanks,
Lorenzo

**Comment by danielepanozzo** [comment] 2017-08-04 22:36
Hi Lorenzo,

This is indeed strange. Could you try to run the binary that you got on win7 (and that works) on the win10 machines, also copying all the relevant dlls? In this way we can rule out a compiler problem.

This sounds like a memory alignment problem or maybe an initialized variable. I unfortunately cannot reproduce it on my end. @gaoxifeng : can you reproduce this problem on your machine?

Daniele

**Comment by AEC-ai** [comment] 2017-08-05 06:38
Hi Daniele,

I've tried both copying the win7 binaries and rebuilding them, and none worked unfortunately. They both fail on that method.

Lorenzo

**Comment by LorenzG** [comment] 2017-08-05 06:50
Hi Daniele,

I've tried both copying the win7 binaries and rebuilding them, and none worked unfortunately. They both fail on that method.
I'm with my old win10 laptop in the next days, but I'll try to put some logs in place and give you more information.

Lorenzo

**Comment by gaoxifeng** [comment] 2017-08-06 02:49
Yes. See below for the screenshot of the output of example 506 on Win10.

![image](https://user-images.githubusercontent.com/19903708/29000117-01da1be8-7a30-11e7-938d-9dac9c7df1a0.png)

**Comment by JiaranZhou** [comment] 2017-08-08 20:15
I met the same problem on mac. Here is the error message:
libc++abi.dylib: terminating with uncaught exception of type std::bad_alloc: std::bad_alloc
Abort trap: 6
I got the same error with example 505, and I believe it is because of igl::copyleft::comiso::miq function.

**Comment by LorenzG** [comment] 2017-08-10 14:44
I think I traced the bug. It should be the following constructor initialization:

igl::HalfEdgeIterator<DerivedF, DerivedTT, DerivedTT> VFI(F, TT, TTi, f_init, indexE)
: fi(_fi), ei(_ei), reverse(_reverse), F(_F), FF(_FF), FFi(_FFi)
{}

and this is the trace:

igl::HalfEdgeIterator<DerivedF, DerivedTT, DerivedTT> VFI(F, TT, TTi, f_init, indexE)
InitMappingSeam(const int vert)
InitMappingSeam()
igl::MeshCutterMini<DerivedV, DerivedF, VFType, DerivedTT, DerivedC> mc(V, F, TT, TTi, VF, VFi, V_border, cuts).InitMappingSeam()
igl::cut_mesh(V, F, VF, VFi, TT, TTi, V_border, cuts, Vcut, Fcut)
igl::cut_mesh(V, F, Handle_Seams, Vcut, Fcut)
igl::copyleft::comiso::MIQ_class<DerivedV, DerivedF, DerivedU>(...)
igl::copyleft::comiso::miq(V, F, PD1_combed, PD2_combed, Handle_MMatch, isSingularity, Handle_Seams, UV, FUV, GradientSize, Stiffness, DirectRound, iter, localIter, DoRound, SingularityRound, roundVertices, hardFeatures)
igl::copyleft::comiso::miq(...).

I guess it has to do with the initialization of those 3 matrices, can you check? Any idea on why and/or how to fix it?

**Comment by danielepanozzo** [comment] 2017-08-18 00:01
It should be fixed with my latest commit. Could you please confirm if it is also fixed for you on windows?

**Comment by LorenzG** [comment] 2017-08-19 09:21
Hi Daniel, thanks for this it all works fine now!

**Closed** 2017-08-19 10:59 UTC
