### ISSUE TITLE
delaunay triangulation crashes

### ISSUE THREAD

**Issue by saedrna** [libigl/libigl#521] opened 2017-04-25 04:58 UTC
Hi,

I would like to use libigl to triangulate a face with holes, that is exported from a sketchup. I use `igl/delaunay_triangulation.h` to do the work and use myself predicates, because sketchup has limited precision set to 0.001. Below is some information of my environment and code to reproduce the crash. The error lies in below, where left_itr is 9 and right is 5.

https://github.com/libigl/libigl/blob/master/include/igl/lexicographic_triangulation.cpp#L95-L105
```cpp
      for (auto itr=left_itr; itr!=right_itr; itr++) {
        if (itr == boundary.end()) itr = boundary.begin();
        if (itr == right_itr) break;
        if (itr == left_itr || itr == right_itr) continue;
        itr = boundary.erase(itr);
        if (itr == boundary.begin()) {
            itr = boundary.end();
        } else {
            itr--;
        }
      }
```

- Environment: Windows 10, 64bit, VS 2015.
- Code to reproduce

```cpp

#include <igl/delaunay_triangulation.h>
#include <Eigen/Core>

constexpr static double EPSILON_LENGTH = 0.0005; // Sketchup support 1/1000 precision
constexpr static double EPSILON_ANGLE = 0.0000000000005;
constexpr static double INV_EPSILON_LENGTH = 2000.0;

template<typename T>
inline int orient2d(const T &pa, const T &pb, const T &pc) {
    double acx, bcx, acy, bcy;
    acx = pa[0] - pc[0];
    bcx = pb[0] - pc[0];
    acy = pa[1] - pc[1];
    bcy = pb[1] - pc[1];

    double val = acx * bcy - acy * bcx;
    if (val < -EPSILON_LENGTH) {
        return -1;
    } else if (val > EPSILON_LENGTH) {
        return 1;
    } else {
        return 0;
    }
    return 0;
}

template <typename T>
inline int incircle(const T &pa, const T &pb, const T &pc, const T &pd) {
    double adx, ady, bdx, bdy, cdx, cdy;
    double abdet, bcdet, cadet;
    double alift, blift, clift;

    adx = pa[0] - pd[0];
    ady = pa[1] - pd[1];
    bdx = pb[0] - pd[0];
    bdy = pb[1] - pd[1];
    cdx = pc[0] - pd[0];
    cdy = pc[1] - pd[1];

    abdet = adx * bdy - bdx * ady;
    bcdet = bdx * cdy - cdx * bdy;
    cadet = cdx * ady - adx * cdy;
    alift = adx * adx + ady * ady;
    blift = bdx * bdx + bdy * bdy;
    clift = cdx * cdx + cdy * cdy;

    double val = alift * bcdet + blift * cadet + clift * abdet;
    if (val < -EPSILON_LENGTH) {
        return -1;
    } else if (val > EPSILON_LENGTH) {
        return 1;
    } else {
        return 0;
    }
    return 0;
}

int main() {
    using namespace Eigen;
    MatrixXd V(16, 2);
    MatrixXi F;

    V << 4.55E-13, 2.33E-12,
        248.718, 249.939,
        463.602, 36.1059,
        764.953, 338.937,
        -1002.42, 2097.68,
        -1303.78, 1794.85,
        -1120.79, 1612.75,
        -1369.5, 1362.81,
        -1552.49, 1544.91,
        -1843.04, 1252.94,
        -75.6625, -505.806,
        214.883, -213.834,
        -191.721, 190.784,
        -1166.14, 1160.44,
        -917.424, 1410.38,
        56.9975, 440.723;

    const auto &orient2d_predicates = [](const double * pa, const double * pb, const double * pc) {
        return orient2d(pa, pb, pc);
    };
    const auto &incircle_predicates = [](const double * pa, const double * pb, const double * pc, const double * pd) {
        return incircle(pa, pb, pc, pd);
    };

    igl::delaunay_triangulation(V, orient2d_predicates, incircle_predicates, F);
    return 0;
}
```

Here is the face to be triangulated,

![qq 20170425124450](https://cloud.githubusercontent.com/assets/3850191/25369478/b6c886fe-29b6-11e7-8c63-20c8cdc91e5b.png)

I would like to ask that if it is my problem to use the code? If yes, please kindly direct me how to solve this issue.

Thanks,
Han

**Comment by alecjacobson** [comment] 2017-04-26 08:06
@qnzhou does this polygon look like an issue to you?

**Comment by qnzhou** [comment] 2017-04-26 15:45
@saedrna I could not reproduce the crash on mac.  I have created a unit test based on your example: https://github.com/qnzhou/libigl-unit-tests/commit/5516ef4ce6f476f4fa1b97cdb6615bdcda614876 and it seems to be fine.

May be it is a Windows specific bug...

**Comment by saedrna** [comment] 2017-04-26 17:32
I have made some debugging, although I don't understand the algorithm, or even what the variable means, I think the problem is about `iter++` as in below. The crash occurs after boundary.erase and iter is set to end and in next iteration iter++ will cause trouble, because this round iter is in an unaccessible value. Maybe this few lines could be refactored?

```cpp
for (auto itr=left_itr; itr!=right_itr; itr++) {
        if (itr == boundary.end()) itr = boundary.begin();
        if (itr == right_itr) break;
        if (itr == left_itr || itr == right_itr) continue;
        itr = boundary.erase(itr);
        if (itr == boundary.begin()) {
            itr = boundary.end();
        } else {
            itr--;
        }
      }
```

**Comment by deuscovrigus** [comment] 2017-08-15 15:26
If you are using the libtriangle delunay triangulation inside igl ( most likely) a crash was fixed by this PR #584 #

**Comment by allo-** [comment] 2018-05-22 09:18
I have the same problem here.

```
    if (itr == boundary.begin()) {
            itr = boundary.end();
        }
```

sets the iterator to ``end()``, which is not the same as ``right_itr``, so the loop increments ``itr``, which is then ``end()+1`` which is invalid.

I am not sure what the algorithm should do after the iterator is set to end. Maybe there should be a ``break`` in there? Or another check in the loop like ``itr!=right_itr && itr != boundary.end()``?

**Comment by allo-** [comment] 2018-05-23 08:16
I wanted to extend the unit test:

	V << 0, 0,
		1, 0,
		0, 1,
		0.57401693531145781, 0.034977512962772302;
	igl::delaunay_triangulation(V, orient2d_predicates, incircle_predicates, F);

But then I discovered that the unit test in https://github.com/qnzhou/libigl-unit-tests/commit/5516ef4ce6f476f4fa1b97cdb6615bdcda614876 already throws the same exception.

**Comment by allo-** [comment] 2019-01-31 12:31
The patched code seems to work as intended here.
Please consider adding this patch to the igl mainline.

**Comment by allo-** [comment] 2019-10-23 14:25
Is there any progress on this?
I am using patched igl files since may 2018 and it would be really nice to be able to use an upstream version that contains the fix.

**Comment by jdumas** [comment] 2019-10-23 14:29
If you already have a unit test and a fix, would you mind submitting a PR into the `dev` branch so we can take a look and integrate it?

**Comment by allo-** [comment] 2019-10-23 15:23
I am not sure with the unit tests. The test linked above is a fork of a (now) read-only repository. Which repository is the official one for unit tests? The tests in the main repo seem to to include the git_issue_XXX tests.

For https://github.com/qnzhou/libigl-unit-tests I probably need to have a look using Linux, because I cannot easily get it to work on this Windows machine.

**Comment by jdumas** [comment] 2019-10-23 15:31
The unit tests are now part of the main libigl repository, under the `tests/` folder, and should work seamlessly on both Windows and Linux.

**Comment by allo-** [comment] 2019-10-23 17:19
Did you change the used test framework in between? I cannot easily use the test case from the link, because it seems to use another test framework.
This means, I probably will need to rewrite the unit test first.

**Comment by jdumas** [comment] 2019-10-23 17:29
Yes we switched from GoogleTest to Catch2. However there are only 2 macros you need to know in Catch2, so the conversion should be fairly straightforward.

**Comment by allo-** [comment] 2019-10-23 17:30
I will have a look.

**Comment by qnzhou** [comment] 2020-02-29 23:13
Ops, sorry for dropping the ball, PR https://github.com/libigl/libigl/pull/1327 looks good me!  Thanks for digging out and fixing this bug.

**Closed** 2020-04-08 21:57 UTC
Labels: bug, pending verification
