### ISSUE TITLE
Can marching_tets work on arbitrary tetrahedral meshes?

### ISSUE THREAD

**Issue by r03ert0** [libigl/libigl#1700] opened 2021-01-17 11:19 UTC
#### Describe your question
I'm trying to use marching_tets to cut through a tetrahedral mesh, using the x coordinate as isovalue. But the result looks like a gruyère. Here's a simple code showing the error:

```python
import numpy as np
import tetgen
import igl
import meshplot as mp

# make a cube
v=np.array([[0,0,0], [0,1,0], [1,1,0], [1,0,0], [0,0,1], [0,1,1], [1,1,1], [1,0,1]], dtype=np.float32)
f=np.array([[0,1,2], [0,2,3], [0,4,5], [0,5,1], [4,7,5], [5,7,6], [7,3,2], [6,7,2], [1,5,2], [2,5,6], [0,3,4],[3,7,4]])

# subdivide it twice, to make a blob
lv, lf = igl.loop(v, f)
lv, lf = igl.loop(lv, lf)

# make a tetrahedral mesh (using tetgen)
tet = tetgen.TetGen(lv, lf)
vv, tt = tet.tetrahedralize(order=1, mindihedral=5000, minratio=1, steinerleft=200)

# compute the isosurface using isovalue=mean(x coordinate)
isovalue = np.mean(vv[:,0])
sv, sf, j, bc = igl.marching_tets(vv, tt, vv[:,0], isovalue)
```
Here's the original blob:

<img width="226" alt="Screenshot 2021-01-17 at 12 18 07" src="https://user-images.githubusercontent.com/2310732/104838913-2607ad80-58be-11eb-889e-88f98d649a4e.png">

Here's the isocontour:
<img width="335" alt="Screenshot 2021-01-17 at 12 18 33" src="https://user-images.githubusercontent.com/2310732/104838916-2acc6180-58be-11eb-86d4-42fe3adbac78.png">

Thank you!

#### Check all that apply (change to `[x]`)
- [ ] Windows
- [x] macOS
- [ ] Linux

**Comment by r03ert0** [comment] 2021-01-18 10:16
two of videos to give more info. First one shows the inside of the tetrahedral mesh (which looks very much ok). The 2nd one gives a better idea of the isocontour result.

https://user-images.githubusercontent.com/2310732/104902022-747c8100-597e-11eb-8dc1-7772f318592d.mov


https://user-images.githubusercontent.com/2310732/104902064-83fbca00-597e-11eb-8bfd-60148f5d1340.mov

**Comment by alecjacobson** [comment] 2021-01-18 14:47
marching_tets doesn't make any assumptions about the input tet mesh (e.g., it doesn't have to be a grid). Tutorial examples 702_WindingNumber, 704_SignedDistance, and 714_MarchingTets are using it and don't appear to be broken.

Your code looks fine to me, so it leads me to guess that this might be an issue with the python bindings. You might repost/ reference this issue over at https://github.com/libigl/libigl-python-bindings/ 

Otherwise, if you can reproduce the error in C++ we could investigate this more here.

**Comment by r03ert0** [comment] 2021-01-18 15:50
thank you! I'll push the issue in the python-bindings repo

**Comment by jdumas** [comment] 2021-01-18 17:06
The marching tet code will not fill the holes if the isosurface intersects the boundary of the tet mesh domain. @chrrt92 has some code to fill the holes created on the boundary tets but it was never pushed as I recall.

Another issue might be resolution, if your tet mesh is too coarse for your SDF you might want to refine it before isocontouring.

**Comment by alecjacobson** [comment] 2021-01-18 17:10
I think in this example the function is just the x-coordinate, so the
result looks bogus and shouldn't depend on resolution.

What do you mean by holes? What would be the function value outside of the
tet mesh?

>

**Comment by jdumas** [comment] 2021-01-18 17:17
Ah yes, if the SDF is the x coordinate then the result look bogus indeed. Might be an assumption about row-major/column-major in the python binding that is screwing up the SDF.

> What do you mean by holes? What would be the function value outside of the
tet mesh?

Imagine the SDF for an infinite cylinder, using a cube tet mesh as the domain. The marching_tet function will create a mesh of a cylinder without the caps (since the facets on the cap will have same sign for the SDF). It's relatively easy to close those holes using the original tet mesh + cut facets, but we don't have the feature yet.

**Comment by alecjacobson** [comment] 2021-01-18 17:22
Got it. Yeah, I also implemented this kind of thing in matlab once. I think
we have marching triangles in libigl, so it should be a matter of combining
them and being careful about matching vertices (maybe that's exactly what
chrrt92 <https://github.com/chrrt92>'s code does).

**Comment by r03ert0** [comment] 2021-01-19 12:42
hi @alecjacobson & @jdumas 
here's the code in C++: the isocontour is all fine. There may be something wrong with the python bindings.

```C++
#include <igl/loop.h>
#include <igl/copyleft/tetgen/tetrahedralize.h>
#include <igl/marching_tets.h>
#include <igl/writePLY.h>
#include <igl/FileEncoding.h>

using namespace std;
using namespace Eigen;

int main(int argc, char *argv[])
{
  MatrixXd v(8,3), lv;
  MatrixXi f(12,3), lf;
  MatrixXd vv;
  MatrixXi tt;
  MatrixXi tf;
  MatrixXd sv;
  MatrixXi sf;

  // make a cube
  v << 0,0,0,  0,1,0,  1,1,0,  1,0,0,
      0,0,1,  0,1,1,  1,1,1,  1,0,1;
  f << 0,1,2,  0,2,3,  0,4,5,  0,5,1,
      4,7,5,  5,7,6,  7,3,2,  6,7,2,
      1,5,2,  2,5,6,  0,3,4,  3,7,4;

  // subdivide it twice, to make a blob
  igl::loop(v, f, lv, lf);
  igl::loop(lv, lf, lv, lf);
  lv = 10.0*lv;
  // make a tetrahedral mesh (using tetgen)
  igl::copyleft::tetgen::tetrahedralize(lv,lf,"pq1.414", vv,tt,tf);
  // compute the isosurface using isovalue=mean(x coordinate)
  double isovalue = 5.0;
  igl::marching_tets(vv,tt,vv.col(0), isovalue, sv,sf);
  igl::writePLY("isosurf.ply",sv,sf, igl::FileEncoding::Ascii);
  return 0;
}
```

<img width="361" alt="Screenshot 2021-01-19 at 13 42 25" src="https://user-images.githubusercontent.com/2310732/105036043-3786bc00-5a5c-11eb-959a-0d6f26110042.png">

**Comment by alecjacobson** [comment] 2021-05-29 17:06
closing this (appears to be python binding issue).

**Closed by alecjacobson** 2021-05-29 17:06 UTC
Labels: python, question
