### ISSUE TITLE
Number of  Threads Global setter

### ISSUE THREAD

**Issue by spyridon97** [libigl/libigl#1715] opened 2021-02-06 01:34 UTC
Hello,

I am currently working on a personal parallel project in which I would like to control the number of threads that are used by IGL
for benchmarking reasons.

I was thinking that maybe there could be a global value and setter that would be like

```c++
#include <thread>
#include <omp.h>

namespace igl
{
    // default value
    size_t num_threads = std::thread::hardware_concurrency();
}

void igl::set_num_threads(const size_t threads)
{
    num_threads = threads;
    // since igl is heavily using openmp (and eigen too)
    omp_set_num_threads(num_threads);
}
```

num_threads would be used for all the parallel_for calls instead of std:: thread ::hardware_concurrency();

What do you think?

#### Check all that apply (change to `[x]`)
- [ X] Windows
- [ X] macOS
- [ X] Linux

**Comment by jdumas** [comment] 2021-02-06 01:43
There is an open PR for that (#1684), but I haven't had time to review it yet. Duplicate of #1683

**Comment by jdumas** [comment] 2021-02-18 16:01
#1684 has been merged.

**Closed by jdumas** 2021-02-18 16:01 UTC
Labels: duplicate, enhancement
