### ISSUE TITLE
Failed to install python binding

### ISSUE THREAD

**Issue by chongkong** [libigl/libigl#1006] opened 2018-11-12 08:18 UTC
## Error Reproduction
I used ubuntu 16.04 latest docker image and latest libigl version (ed363da1f624e7a2f802f6b04973be8ea63f0511) to reproduce the error.

- Clone fresh `libigl`
- Build from source root (hereandafter `$LIBIGL`) with cmake
- Manually clone `pybind11` into `$LIBIGL/external`
- Build from `$LIBIGL/python` as python binding installation steps described in doc:

```shell
cd python
mkdir build
cd build; cmake ..; make; cd ..
```

This doesn't seem to set `INCLUDE_DIRECTORIES` properly. Running `make` emits an error message saying that it failed to locate `Eigen` header directory correctly.

Here's the full error message.

``` shell
Scanning dependencies of target pyigl
[ 16%] Building CXX object CMakeFiles/pyigl.dir/python_shared.cpp.o
[ 33%] Building CXX object CMakeFiles/pyigl.dir/py_igl.cpp.o
[ 50%] Building CXX object CMakeFiles/pyigl.dir/modules/py_vector.cpp.o
[ 66%] Building CXX object CMakeFiles/pyigl.dir/py_doc.cpp.o
/workspace/libigl/python/modules/py_vector.cpp:8:10: fatal error: Eigen/Geometry: No such file or directory
 #include <Eigen/Geometry>
          ^~~~~~~~~~~~~~~~
compilation terminated.
/workspace/libigl/python/py_igl.cpp:8:10: fatal error: Eigen/Dense: No such file or directory
 #include <Eigen/Dense>
          ^~~~~~~~~~~~~
compilation terminated.
CMakeFiles/pyigl.dir/build.make:86: recipe for target 'CMakeFiles/pyigl.dir/modules/py_vector.cpp.o' failed
make[2]: *** [CMakeFiles/pyigl.dir/modules/py_vector.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/pyigl.dir/build.make:110: recipe for target 'CMakeFiles/pyigl.dir/py_igl.cpp.o' failed
make[2]: *** [CMakeFiles/pyigl.dir/py_igl.cpp.o] Error 1
In file included from /workspace/libigl/python/python_shared.cpp:8:0:
/workspace/libigl/python/python_shared.h:16:10: fatal error: Eigen/Dense: No such file or directory
 #include <Eigen/Dense>
          ^~~~~~~~~~~~~
compilation terminated.
CMakeFiles/pyigl.dir/build.make:62: recipe for target 'CMakeFiles/pyigl.dir/python_shared.cpp.o' failed
make[2]: *** [CMakeFiles/pyigl.dir/python_shared.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/pyigl.dir/all' failed
make[1]: *** [CMakeFiles/pyigl.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
```

## Additional Issue

The python binding build process stated in the doc lacks the process to install them in python. If I try to install the whole directory using `pip`, or running `setup.py` manually, some different kinds of errors pop up:

```
    CMake Error at CMakeLists.txt:29 (include):
      include could not find load file:

        libigl


    CMake Error at CMakeLists.txt:34 (add_subdirectory):
      add_subdirectory given source
      "/tmp/pip-ctjzf1n_-build/../external/pybind11" which is not an existing
      directory.


    CMake Error at CMakeLists.txt:37 (pybind11_add_module):
      Unknown CMake command "pybind11_add_module".


    -- Configuring incomplete, errors occurred!
```

I would appreciate if you provide a guidance on installing `pyigl` in my python as well.

#### Check all that apply (change to `[x]`)
- [ ] Windows
- [x] Mac OS X
- [x] Linux

**Comment by jdumas** [comment] 2018-11-12 14:58
Hi. New python bindings are in the work on the `dev-python` branch, so I encourage you to try those if you are having issues with the current bindings (disclaimer: the new bindings are not complete/ready yet). That being said, the way to build the python bindings right now is to build from the root folder. No need to manually clone `pybind11` or build from the `python/` folder.

**Comment by chongkong** [comment] 2018-11-12 16:21
Thanks, @jdumas! I'll check it out

**Comment by jdumas** [comment] 2018-11-13 22:18
I've pushed some fixes in #1008, waiting to be merged. Please use this to build your python bindings and try building from the root folder.

**Comment by chongkong** [comment] 2018-11-16 07:29
Sorry for the late followup. I really appreciate your work on helping my issue. I took a look on your commits, but I think it doesn't really make `pyigl` installable.

To my knowledge, if you want to install `pyigl` via `pip`, you have to build the project via `setup.py`, not manual building from the root project. Of course, you'll get your `.so` file which, if placed in `site-packages` properly, can be imported in python and works well. But that's not how python package installation in the client side should be done.

After few trials and errors, I figured out `pip` makes an isolated environment somewhere inside `/tmp` folder, copying entire directory in which `setup.py` is located recursively. Therefore if `setup.py` is located in subdirectory of the project root, (currently `python`) other sibling directories (including `cmake` and `include`) will not be visible to `setup.py` and thus pip will not be able to run `cmake` correctly.

I believe `setup.py` should be **moved to project root directory** and `CMakeBuild` should make `cmake` call on its `python` subdirectory. Here's the working solution

``` diff python
# setup.py

class CMakeBuild(build_ext):
    ...
    def build_extension(self, ext):
        ...
-       subprocess.check_call(['cmake', ext.source_dir] + cmake_args, 
+       subprocess.check_call(['cmake', os.path.join(ext.source_dir, 'python')] + cmake_args,
                              cwd=self.build_temp)
        ...
```

I'm not 100% sure this is the right way, so further discussion is welcome.

**Comment by jdumas** [comment] 2018-11-16 07:40
Right now pyigl is not installable. The new python bindings (in the `dev-python` branch) will be, but they are not ready yet.

**Comment by alecjacobson** [comment] 2019-02-05 15:35
Is there a status update on this issue? (Asking for a friend, literally)

**Comment by ladzin** [comment] 2019-02-05 15:38
I'm that friend :) I had similar include errors when trying to compile on Win64. I read the messages above but I'm not clear on what is the solution.

**Comment by jdumas** [comment] 2019-02-05 15:44
Afaik the python bindings are building on AppVeyor, so if moving the `setup.py` to the root folder is all it takes to make the repo installable via pip, then I say we go for it (the new `python-dev` branch hasn't seen much progress lately, and looks like it's gonna take a while still :p).

**Comment by bmahlbrand** [comment] 2019-05-17 06:46
Has there been any updates with this issue?

**Comment by jdumas** [comment] 2019-05-18 10:22
As fair as I know the python bindings build fine in the `dev` branch (follow the steps in the `.appveyor.yml` or `.travis.yml` files to reproduce). It may still lack the ability to install via `pip` (we'd need to move the `setup.py` into the root folder?), but that should prevent you from compiling and using libigl (albeit in a bit more cumbersome way for now). New python bindings are in the work and should be ready for a SIGGRAPH course this summer.

**Comment by bmahlbrand** [comment] 2019-05-18 23:35
Exciting! Looking forward to it. I assume you meant "...shouldn't* prevent you..."

Thought I'd check in before losing time to something that wasn't working to begin with.

**Comment by jdumas** [comment] 2019-05-18 23:37
>  I assume you meant "...shouldn't* prevent you..."
Right. I fixed the typo.

**Comment by oracle3001** [comment] 2019-06-02 11:15
I have successfully built the binding from the dev branch on a windows using VS2017. It produces a .pyd, which as a python newbie I understand is similar to a dll and can be placed in the same directory as the python script which is trying to use it.

When I do this and call 

import pyigl as igl

I get the following error 

Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Professional Edition with Anaconda plugin 2019.1.1\helpers\pydev\_pydevd_bundle\pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<string>", line 2, in <module>
  File "C:\Program Files\JetBrains\PyCharm Professional Edition with Anaconda plugin 2019.1.1\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ImportError: DLL load failed: The specified module could not be found.

**Comment by bmahlbrand** [comment] 2019-06-02 12:18
https://askubuntu.com/questions/470982/how-to-add-a-python-module-to-syspath

When I did this 6 or so months back, the solution was along these lines.

**Comment by teseoch** [comment] 2020-02-20 15:41
this issue involves the old bindings which have been discontinued, plz refer to https://libigl.github.io/libigl-python-bindings/ for the new version.

You can install the python version trough conda

**Closed by teseoch** 2020-02-20 15:41 UTC
Labels: python
