### ISSUE TITLE
<IGL/IO> IOError : stl file could not be reopened as binary (1) [VS2015-x86-x64]

### ISSUE THREAD

**Issue by TsubameDono** [libigl/libigl#631] opened 2017-11-02 16:26 UTC
Hi,

I love IGL, I use it mainly to experiment my mesh processing algorithms and advise its uses.
Recently, I need to use STL format for works but I have some issues using IO functions as readSTL, readPLY

for STL I get this error :
        IOError : stl file could not be reopened as binary (1)
However my files use ASCII format (and even for binary format it doesn't work at all)

If someone has already get this error when compiling LibIGL with Visual Studio 2015 (v140) can he/she tell how resolve this error ?

Thanks ❤️

**Comment by alecjacobson** [comment] 2017-11-02 17:53
This seems to be a duplicate of https://github.com/libigl/libigl/issues/625

**Closed by alecjacobson** 2017-11-02 17:53 UTC
