### ISSUE TITLE
decimate will not work correctly on non-edge-manifold meshes

### ISSUE THREAD

**Issue by LogWell** [libigl/libigl#2043] opened 2022-05-24 13:27 UTC
Here is an example file: https://rec.ustc.edu.cn/share/2e9c8f10-db65-11ec-b0eb-cbbf186540e6

This mesh works fine in meshlab.
How can I run the decimate function in igl?

```
    igl::qslim(igl_V, igl_F, PARAM_max_m, igl_U, igl_G, igl_J, igl_I);
    igl::decimate(igl_V, igl_F, PARAM_max_m, igl_U, igl_G, igl_J, igl_I);
```

**Comment by alecjacobson** [comment] 2022-05-26 23:32
This mesh appears to be edge-manifold (that's good). It does have boundaries; that should be OK. **but** it has two non-manifold vertices. This is not OK and decimate will not work correctly. As described in header, our implementation assumes that the mesh is manifold https://github.com/libigl/libigl/blob/30019acb17197abb6f3fe4c310909c817f2e85cc/include/igl/decimate.h#L15

A couple options:
  - run a tool like meshfix on your input first https://github.com/alecjacobson/MeshFix-V2.1
  - write your own cost function that assigns infinite cost to any edge touching a non-manifold vertex (I _think_ that this will work, but I'm not 100% sure.)
  - write a new function that duplicates non-manifold vertices and splits them combinatorially. This is likely the best option. I might get intrigued enough to write out a solution, but no promises.

Rewriting decimate to handle non-manifold meshes would be pretty daunting. I'm not sure exactly what that would look like. It's probably not going to happen with small changes, but rather a full rewrite. I'd be curious to know what meshlab does for this case.
  
For now, closing this as, it's not a bug. Happy to continue the conversation or accept a PR if you implement a fix.

**Closed by alecjacobson** 2022-05-26 23:32 UTC
Labels: bug, pending verification

**Comment by jdumas** [comment] 2022-05-27 02:03
> write a new function that duplicates non-manifold vertices and splits them combinatorially. This is likely the best option. I might get intrigued enough to write out a solution, but no promises.

There is [such a function](https://opensource.adobe.com/lagrange-docs/user/core/mesh-cleanup/#resolve-nonmanifoldness=) already in Lagrange btw, in case you're interested.

**Comment by alecjacobson** [comment] 2022-05-27 04:56
I also forgot that I'd implemented this in gptoolbox. I've ported it to libigl in #2047
