### ISSUE TITLE
iterating over adjacent edges

### ISSUE THREAD

**Issue by avaxman** [libigl/libigl#399] opened 2016-11-15 20:56 UTC
Is there any way to iterate over all edges adjacent to a vertex in some order? corresponding with the edge indices you get in edge_topology().

**Comment by alecjacobson** [comment] 2016-11-15 21:00
`edge_topology` is an obsolete, inferior duplicate of `edge_flaps`. It will
be removed in the future.

With `edge_flaps` (similar output as `edge_topology`) you can use
`igl::circulation` to travel around a vertex. circulation returns indices
to faces but from this you can easily determine the "spoke" edges or
"one-ring" vertices. See, for example, its use in `collapse_edge`

Currently this is only valid for manifold meshes, but probably what you
want to do won't make sense for non-manifold meshes anyway.

**Comment by avaxman** [comment] 2016-11-15 21:05
The explanation is vague ("touched by circulation?"). Is the list sorted?

**Comment by alecjacobson** [comment] 2016-11-15 21:51
yes, circulations are cyclically sorted.

**Comment by avaxman** [comment] 2016-11-22 08:55
I should note that I put a DCEL structure in libhedra:
https://github.com/avaxman/libhedra ("dcel.h")
it returns matrices (the libigl way) and comfortable to work with in manners of circulation etc.

**Comment by alecjacobson** [comment] 2016-11-22 14:22
neat!

**Closed by alecjacobson** 2016-11-22 14:22 UTC
