### ISSUE TITLE
Errors on sparse.cpp

### ISSUE THREAD

**Issue by azer89** [libigl/libigl#2] opened 2014-03-24 11:30 UTC
Hi, I got this error on Sparse.cpp:

My VS on windows says:
	1	IntelliSense: no instance of overloaded function "igl::sparse" matches the specified type	d:\VG_Project\BBW_LIBIGL\BBW_LIBIGL\igl\sparse.cpp	115

Error	8	error C2977: 'igl::sparse' : too many template arguments	d:\vg_project\bbw_libigl\bbw_libigl\igl\sparse.cpp	115

Error	9	error C2977: 'igl::sparse' : too many template arguments	d:\vg_project\bbw_libigl\bbw_libigl\igl\sparse.cpp	115

I define these preprocessors on my project:
IGL_NO_OPENGL
IGL_NO_ANTTWEAKBAR
IGL_NO_MOSEK
EIGEN_YES_I_KNOW_SPARSE_MODULE_IS_NOT_STABLE_YET

**Comment by jiangzhongshi** [comment] 2016-03-15 05:38
Got the same problem. libigl updated today. at line 114 inside ifdef _WIN32

**Comment by danielepanozzo** [comment] 2016-03-15 18:47
I cannot reproduce this, does it happen when you compile the tutorials? The windows build on the latest commit was successful: https://ci.appveyor.com/project/danielepanozzo/libigl-6hjk1

Could you provide a minimal example to reproduce this?

**Comment by jiangzhongshi** [comment] 2016-03-16 09:01
Yes, while compiling the tutorials.

The first error was at line 1111 of AABB.h, where VS doesn't support '#if false'. So I change it to '#if 0'

After that, alignment issue of Eigen arise in project igl and I added EIGEN_DONT_ALIGN to the preprocessor .

Next, '#elif false' at line 27 of random_quaternion.cpp. Fix again. Then there's the issue in sparse.cpp

When I commented this line, it successfully compiles, but I don't think this is the right solution.

Thanks!

**Comment by jiangzhongshi** [comment] 2016-03-16 09:02
I forgot to mention: VS2013 professional, CMAKE-GUI.

Thanks

**Comment by jiangzhongshi** [comment] 2016-03-16 09:36
I was using 32-bit build, so maybe I'll try again with 64-bit version, as mentioned in the tutorial

**Comment by danielepanozzo** [comment] 2016-03-16 12:45
Yes please try with 64-bit and possibly with VS 2015. It is difficult to keep the entire codebase compatible with all the different flavors of VS, each one of them has its perks and none is really respecting the c++ standards. We are currently supporting only VS 2015 since our time for supporting libigl is quite limited, but if you can fix it for VS 2013 please send a pull request. After you send the pull request, our autobuilds will test it with VS 2015 and if it passes the build there I will integrate it in the main repo.

**Comment by jiangzhongshi** [comment] 2016-03-18 06:08
Thanks, it successfully builds & compiles with VS2015x64.

However, there is a remaining issue when LIBIGL_WITH_NANOGUI option is enabled.
The resulting solution has no project "glew" as there would be in default setting, which leads to a link error (cannot open 'glew.lib').

**Comment by danielepanozzo** [comment] 2016-03-21 04:18
Fixed in 6a285a1dfafcc3a39133607c4c3d569207fa8a49. Could you please test it and close the ticket if it is also solved on your system?

**Comment by jiangzhongshi** [comment] 2016-04-14 01:49
Sorry for the late reply. Yes, it did works! Thanks a lot!

**Closed** 2016-04-14 02:25 UTC

**Comment by lin-ht** [comment] 2017-01-13 19:25
I got the same error, "error C2977: 'igl::sparse' : too many template arguments", using VS2013 &Win32. 
I solved this problem by replacing the input parameter type "unsigned long" with "size_t".
Will this modification bring in any defects/bug?

**Comment by lin-ht** [comment] 2017-01-13 21:36
Other errors are solved similarly as @jiangzhongshi, except the error '#if false'. I added option -Dfalse=(!1) -Dtrue=(!0) in the compiling command to define false and true.
