### ISSUE TITLE
No such file or directory error when compiling my cmake file

### ISSUE THREAD

**Issue by YemmyMMU** [libigl/libigl#1158] opened 2019-04-17 15:10 UTC
[Describe your issue]

I am trying to run make on the below cmake file and run into this error "No such file or directory"

This is my cmake file:

#include <igl/readOFF.h>
#include <igl/opengl/glfw/Viewer.h>
#include <igl/cat.h>
#include <igl/edge_lengths.h>
#include <igl/readPLY.h>
#include <igl/readOBJ.h>

#include <igl/edge_lengths.h>
#include <igl/parula.h>
#include <igl/per_edge_normals.h>
#include <igl/per_face_normals.h>
#include <igl/per_vertex_normals.h>
#include <igl/point_mesh_squared_distance.h>
#include <igl/signed_distance.h>
#include <igl/WindingNumberAABB.h>
#include <igl/parallel_for.h>
#include <igl/upsample.h>
#include <igl/parser.h>
#include <Eigen/Sparse>

#include
#include
#include
#include

// #include
// #include <boost/filesystem.hpp>

#include "tutorial_shared_path.h"

using namespace std;

Eigen::MatrixXd V;
Eigen::MatrixXd normalizedV;
Eigen::MatrixXi F;
Eigen::MatrixXd GV;
Eigen::VectorXd S_signed;
igl::AABBEigen::MatrixXd,3 tree;

The error is as follows:
ajayi@apollo:/singed/build$ cmake ..
-- Creating target: igl::core (igl)
-- Using header-only CGAL
-- Targetting Unix Makefiles
-- Using /usr/bin/c++ compiler.
-- __cplusplus is 201103
-- --> Do not link with Boost.Thread
-- Boost version: 1.58.0
-- Boost include dirs: /usr/include
-- Boost libraries:
-- Boost version: 1.58.0
-- Found the following Boost libraries:
-- thread
-- system
-- chrono
-- date_time
-- atomic
-- Using gcc version 4 or later. Adding -frounding-math
-- Creating target: igl::cgal (igl_cgal)
-- Creating target: igl::opengl (igl_opengl)
-- Creating target: igl::opengl_glfw (igl_opengl_glfw)
-- Using X11 for window creation
-- Boost version: 1.58.0
-- Found the following Boost libraries:
-- filesystem
-- system
-- Configuring done
-- Generating done
-- Build files have been written to: /singed/build
ajayi@apollo:/build$ make
[ 9%] Built target glad
[ 90%] Built target glfw
Scanning dependencies of target sdf_bin
[ 95%] Building CXX object CMakeFiles/sdf_bin.dir/main.cpp.o
/singed/main.cpp:1:25: fatal error: igl/readOFF.h: No such file or directory
#include <igl/readOFF.h>
^
compilation terminated.
CMakeFiles/sdf_bin.dir/build.make:62: recipe for target 'CMakeFiles/sdf_bin.dir/main.cpp.o' failed
make[2]: *** [CMakeFiles/sdf_bin.dir/main.cpp.o] Error 1
CMakeFiles/Makefile2:708: recipe for target 'CMakeFiles/sdf_bin.dir/all' failed
make[1]: *** [CMakeFiles/sdf_bin.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

Pls kindly help!
#### Check all that apply (change to `[x]`)
- [ ] Windows
- [ ] Mac OS X
- [x ] Linux

See <https://libigl.github.io/CONTRIBUTING/#bugreport> for more tips.

**Comment by jdumas** [comment] 2019-04-17 15:16
Duplicate of #1154

**Closed** 2019-04-17 15:16 UTC
