### ISSUE TITLE
Import Error with pyigl as igl

### ISSUE THREAD

**Issue by woahitsjc** [libigl/libigl#317] opened 2016-08-07 17:31 UTC
When trying to launch a libigl tutorial in my command line, it produces:
ImportError: No module named 'pyigl'

This error is pointed towards the line, import pyigl as igl.

Any help would be appreciated, thanks!

**Comment by danielepanozzo** [comment] 2016-08-08 14:22
Did you compile the python bindings before running the tutorials?

cd libigl/python
mkdir build
cd build
cmake ../
make

**Comment by woahitsjc** [comment] 2016-08-08 17:09
I have done that already.

**Comment by danielepanozzo** [comment] 2016-08-08 19:24
Mmm then it is likely that you have multiple versions of python installed and that you are building the library with one version and trying to run the python script with another.

**Comment by woahitsjc** [comment] 2016-08-19 18:33
Hi, sorry I haven't responded for some time. I actually forgot to use the make command. However, I am not really sure how to use it. I tried using it with mingw32 and gnuwin but I needed to specify a target and a makefile (which I have no idea what to input).

**Comment by danielepanozzo** [comment] 2016-08-19 19:01
You need to compile it with VS2015, it will not work with mingw. I will close this issue since the problem is now clear.

**Closed by danielepanozzo** 2016-08-19 19:01 UTC

**Comment by maria-korosteleva** [comment] 2018-07-17 04:47
I have a very similar problem. While compiling the python bindings I executed the cmake .. command. It seemed successful, but there is no makefile created in a build directory, so I receive an error 
make: *** No targets specified and no makefile found.  Stop.
Does this mean that the compilation with cmake went wrong? 

I used cmake with VS 15 2017 Win64, compiled for python 2.7

**Comment by jdumas** [comment] 2018-07-17 14:05
This looks like a different problem. And if you are using Visual Studio, you should not compile with `make`, but instead you should open the `.sln` generated by CMake, and compile it within VS.

**Comment by maria-korosteleva** [comment] 2018-07-18 02:01
Thank you very much! It worked

**Comment by torkan-gh** [comment] 2019-09-13 13:02
Hi, 
I want to compile the python binding on windows, though I get such an error as a result of bellow commands:
cd libigl/python
mkdir build
cd build
cmake .. -G "Visual Studio 15 2017 Win64"

-- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.17134.
CMake Error at CMakeLists.txt:8 (message):
  Trying to compile Python bindings without -DLIBIGL_WITH_PYTHON=ON.  Either
  enable manually all the necessary options, or compile from the root folder
  with -DLIBIGL_USE_STATIC_LIBRARY=OFF

**Comment by fwilliams** [comment] 2019-09-13 15:04
Hi, you may want to try the new libigl python bindings available on conda (just `conda install -c conda-forge igl`). They're still in beta and missing some functions, but they're much easier to use and directly compatible with numpy/scipy. 

Tutorial is [here](https://geometryprocessing.github.io/libigl-python-bindings/tutorials/)
Function reference is [here](https://geometryprocessing.github.io/libigl-python-bindings/igl_docs/)

**Comment by LoveJoan99** [comment] 2019-10-26 02:41
> y idea of how can I handle this problem?



> Hi,
> I want to compile the python binding on windows, though I get such an error as a result of bellow commands:
> 
> cd libigl/python
> mkdir build
> cd build
> cmake .. -G "Visual Studio 15 2017 Win64"
> 
> -- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.17134.
> CMake Error at CMakeLists.txt:8 (message):
> Trying to compile Python bindings without -DLIBIGL_WITH_PYTHON=ON. Either
> enable manually all the necessary options, or compile from the root folder
> with -DLIBIGL_USE_STATIC_LIBRARY=OFF
> 
> any idea of how can I handle this problem?



> Hi,
> I want to compile the python binding on windows, though I get such an error as a result of bellow commands:
> 
> cd libigl/python
> mkdir build
> cd build
> cmake .. -G "Visual Studio 15 2017 Win64"
> 
> -- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.17134.
> CMake Error at CMakeLists.txt:8 (message):
> Trying to compile Python bindings without -DLIBIGL_WITH_PYTHON=ON. Either
> enable manually all the necessary options, or compile from the root folder
> with -DLIBIGL_USE_STATIC_LIBRARY=OFF
> 
> any idea of how can I handle this problem?

have you handle this problem? I meet the same problem, can you make any help?

**Comment by LoveJoan99** [comment] 2019-10-26 02:44
Have you handle your problem, I meet the same problem. Can you please make give me any help ?@torkan-gh

**Comment by LoveJoan99** [comment] 2019-10-26 02:45
> Hi,
> I want to compile the python binding on windows, though I get such an error as a result of bellow commands:
> 
> cd libigl/python
> mkdir build
> cd build
> cmake .. -G "Visual Studio 15 2017 Win64"
> 
> -- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.17134.
> CMake Error at CMakeLists.txt:8 (message):
> Trying to compile Python bindings without -DLIBIGL_WITH_PYTHON=ON. Either
> enable manually all the necessary options, or compile from the root folder
> with -DLIBIGL_USE_STATIC_LIBRARY=OFF
> 
> any idea of how can I handle this problem?

Have you handle your problem, I meet the same problem. Can you please make give me any help ?@torkan-gh

**Comment by jdumas** [comment] 2019-10-26 06:51
Hi,

You may want to try out our new python bindings [here](https://geometryprocessing.github.io/geometric-computing-python/).

**Comment by Lennon-di** [comment] 2020-07-14 06:59
> This looks like a different problem. And if you are using Visual Studio, you should not compile with `make`, but instead you should open the `.sln` generated by CMake, and compile it within VS.

After opening the libigl-tutorials.sln , the only tutorial I see in Visual Studio is the first one -101_FileIO .  How could I solve this issue?

**Comment by jdumas** [comment] 2020-07-14 07:06
You probably generated your CMake project from `tutorials/CMakeLists.txt` instead of `<libigl>/CMakeLists.txt` at the root of the repository. I suggest either using the root CMakeLists.txt, or enabling specific options (e.g. `LIBIGL_WITH_OPENGL` and `LIBIGL_WITH_OPENGL_GLFW`) to enable the OpenGL viewer necessary for the other tutorials. Those options can be enabled via CMake GUI.
