### ISSUE TITLE
Failed to install python binding with dev-python branch

### ISSUE THREAD

**Issue by bednarikjan** [libigl/libigl#1041] opened 2018-12-04 18:10 UTC
# Problem
Building of python bindings fails when using the code in **dev-python** branch. I use macOS 10.13.6 with clang-1000.11.45.5. Note that I first built libigl using **master** branch, then I switched to **dev-python** branch to build the Python bindings, as in the master branch the build fails as well as summarized in Issue #1006.

# Error reproduction
* Clone and build libigl as described in the [tutorial](https://libigl.github.io/tutorial/).
* Checkout dev-python branch.
* Build python bindings as described in the [tutorial](https://libigl.github.io/python-bindings/#installation).

During building, the following error appears:

```
In file included from .../libigl/python/build/principal_curvature.out.cpp:5:
In file included from .../libigl/cmake/../include/igl/principal_curvature.h:65:
.../libigl/cmake/../include/igl/principal_curvature.cpp:784:22: error: out-of-line definition of
      'principal_curvature' does not match any declaration in namespace 'igl'
IGL_INLINE void igl::principal_curvature(
                     ^~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/pyigl.dir/principal_curvature.out.cpp.o] Error 1
```
# Platforms
- [ ] Windows
- [x] Mac OS X
- [ ] Linux

**Comment by jdumas** [comment] 2018-12-04 21:33
Hi. Thanks for your report. I'm closing this as a duplicate of #1006. The `dev-python` branch is a work in progress and is not expected to work in all situations yet. For now I suggest to use the `dev` branch if you need working python bindings (a fix has been pushed in #1008). Please continue the discussion in #1006 if you need additional help working with the current python bindings, or discuss the work-in-progress `dev-python` branch.

**Closed by jdumas** 2018-12-04 21:33 UTC
Labels: duplicate, python
